# Required: A short name for the action package
name: home-lab-actions

# Required: A description of what's in the action package.
description: Action package description

# Package version number, recommend using semver.org
version: 0.0.1

# Specify the spec version
spec-version: v2

dependencies:
  conda-forge:
  - python=3.12.0
  - uv=0.7.13
  pypi:
  - sema4ai-actions=1.3.15
  - paramiko=3.5.1
  - python-dotenv=1.1.1
  - kubernetes=33.1.0

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
