name: Build and Push Home Lab Actions Docker Image

on:
  push:
    paths:
      - 'package.yaml'
      - 'Dockerfile'
      - 'src/**'
      - 'config/**'
  pull_request:
    paths:
      - 'package.yaml'
      - 'Dockerfile'
      - 'src/**'
      - 'config/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # was: read
      packages: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set lowercase IMAGE_NAME
        id: set_image_name
        run: |
          IMAGE_NAME=$(echo "${{ github.repository_owner }}/home-lab-actions" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Log in to Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5.7.0
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set NEW_TAG output
        id: set_tag
        run: |
          TAGS="${{ steps.meta.outputs.tags }}"
          # Get the first tag that is not 'latest', keep the full image:tag string
          NEW_TAG=$(echo "$TAGS" | tr ',' '\n' | grep -v ':latest' | head -n1)
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

   